[project]
name = "r2k8s"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.0",
    "uvicorn",
    "jinja2",
    "gunicorn",
    "httpx>=0.27.2",
]
